# Site settings
title: Thiago Rodrigues
description: "A blog about me and things that i build ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://undersfx.github.io/" # for test: remove string to '' but in production: 'https://yourusername.github.io'

# User settings
username: undersfx
user_title: Thiago Rodrigues
email: thiago.rfr@hotmail.com
twitter_username: undersfx
github_username:  undersfx
gplus_username:  undersfx
linkedin_public_url: trfrodrigues # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username:
profile_picture: https://avatars1.githubusercontent.com/u/7119450?s=400&u=0e31fc7ceeaf1463c063c5e15607db1abefb9f82&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/undersfx
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/undersfx
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: sndslib
    url: https://github.com/undersfx/sndslib

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
